# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 241b56e5d1c234087c5773fead9b80e65a9bc071fe83d9edb0e0808e72957e1440587bba9488b5e5929263999cfa71cc395c313e8332edbbf2bc63819bf4dfb2

test:
  secret_key_base: 1de9402b0f61344d3da594eef6e685a44da2690653d40b41826f5c29ce014e76962aef650bf80227edc76864dfd495445698b8d7d7e75522d274d05a036035fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
